/**
 * @license MIT
 * @see https://eslint.org/docs/latest/rules/
 * @see https://github.com/freaktechnik/eslint-plugin-array-func#rules
 * @see https://eslint-community.github.io/eslint-plugin-eslint-comments/rules/
 * @see https://github.com/un-ts/eslint-plugin-import-x#rules
 * @see https://github.com/gajus/eslint-plugin-jsdoc#rules
 * @see https://github.com/mozilla/eslint-plugin-no-unsanitized#rule-details
 * @see https://github.com/eslint-community/eslint-plugin-promise#rules
 * @see https://github.com/eslint-community/eslint-plugin-security#rules
 * @see https://ota-meshi.github.io/eslint-plugin-regexp/rules/
 * @see https://github.com/sindresorhus/eslint-plugin-unicorn#rules
 * @author Sébastien Règne
 */

import comments from "@eslint-community/eslint-plugin-eslint-comments";
// https://github.com/freaktechnik/eslint-plugin-array-func/issues/492
// @ts-expect-error -- Le plugin array-func ne fournit pas de types.
// https://github.com/freaktechnik/eslint-plugin-array-func/pull/661
// eslint-disable-next-line importX/no-rename-default
import arrayFunc from "eslint-plugin-array-func";
// La dépendance "@typescript-eslint/utils" a été ajoutée, car elle est
// nécessaire pour vérifier les types de "eslint-plugin-import-x".
// https://github.com/un-ts/eslint-plugin-import-x/issues/475
import { importX } from "eslint-plugin-import-x";
// eslint-disable-next-line importX/no-rename-default, importX/no-named-as-default
import jsdoc from "eslint-plugin-jsdoc";
// https://github.com/mozilla/eslint-plugin-no-unsanitized/pull/271
// @ts-expect-error -- Le plugin no-unsanitized ne fournit pas de types.
import noUnsanitized from "eslint-plugin-no-unsanitized";
// https://github.com/eslint-community/eslint-plugin-promise/issues/488
// @ts-expect-error -- Le plugin promise ne fournit pas de types.
import promise from "eslint-plugin-promise";
import regexp from "eslint-plugin-regexp";
import security from "eslint-plugin-security";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";

/**
 * @import { Linter } from "eslint"
 */

/**
 * @type {Linter.Config}
 */
export default {
    languageOptions: {
        globals: globals["shared-node-browser"],
    },

    linterOptions: {
        reportUnusedInlineConfigs: "error",
    },

    plugins: {
        arrayFunc,
        comments,
        importX,
        jsdoc,
        noUnsanitized,
        promise,
        regexp,
        security,
        unicorn,
    },

    rules: {
        // Possible Problems.
        "array-callback-return": "error",
        "constructor-super": "error",
        "for-direction": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-await-in-loop": "off",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": [
            "error",
            { checkRelationalComparisons: true },
        ],
        "no-constant-condition": "error",
        "no-constructor-return": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "error",
        "no-ex-assign": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-inner-declarations": ["error", "both"],
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": [
            "error",
            {
                skipStrings: false,
                skipComments: false,
                skipRegExps: false,
                skipTemplates: false,
            },
        ],
        "no-loss-of-precision": "error",
        "no-misleading-character-class": ["error", { allowEscape: true }],
        "no-new-native-nonconstructor": "error",
        "no-new-symbol": "error",
        "no-obj-calls": "error",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-this-before-super": "error",
        "no-unassigned-vars": "error",
        "no-undef": "error",
        "no-unexpected-multiline": "error",
        "no-unmodified-loop-condition": "error",
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
        "no-unsafe-optional-chaining": [
            "error",
            {
                disallowArithmeticOperators: true,
            },
        ],
        "no-unused-private-class-members": "error",
        "no-unused-vars": [
            "error",
            {
                args: "all",
                argsIgnorePattern: "^_",
                caughtErrorsIgnorePattern: "^_",
            },
        ],
        "no-use-before-define": "error",
        "no-useless-backreference": "error",
        "require-atomic-updates": "off",
        "use-isnan": [
            "error",
            {
                enforceForSwitchCase: true,
                enforceForIndexOf: true,
            },
        ],
        "valid-typeof": "error",

        // Suggestions.
        "accessor-pairs": ["error", { enforceForClassMembers: true }],
        "arrow-body-style": "off",
        "block-scoped-var": "error",
        camelcase: "error",
        "capitalized-comments": [
            "error",
            "always",
            {
                ignorePattern: "biome-ignore|prettier-ignore",
                ignoreConsecutiveComments: true,
            },
        ],
        "class-methods-use-this": "error",
        complexity: ["warn", { max: 50, variant: "modified" }],
        "consistent-return": "error",
        "consistent-this": "error",
        curly: "error",
        "default-case": "error",
        "default-case-last": "error",
        "default-param-last": "error",
        "dot-notation": ["error", { allowKeywords: true, allowPattern: "_" }],
        eqeqeq: "error",
        "func-name-matching": ["error", { considerPropertyDescriptor: true }],
        "func-names": ["error", "as-needed"],
        "func-style": "error",
        "grouped-accessor-pairs": ["error", "getBeforeSet"],
        "guard-for-in": "error",
        "id-denylist": "off",
        "id-length": "off",
        "id-match": "off",
        "init-declarations": "off",
        "logical-assignment-operators": [
            "error",
            "always",
            {
                enforceForIfStatements: true,
            },
        ],
        "max-classes-per-file": "error",
        "max-depth": ["warn", { max: 5 }],
        "max-lines": [
            "warn",
            {
                max: 1000,
                skipBlankLines: true,
                skipComments: true,
            },
        ],
        "max-lines-per-function": [
            "warn",
            {
                max: 100,
                skipBlankLines: true,
                skipComments: true,
            },
        ],
        "max-nested-callbacks": "warn",
        "max-params": ["warn", { max: 5 }],
        "max-statements": ["warn", { max: 50 }],
        "new-cap": "error",
        "no-alert": "error",
        "no-array-constructor": "error",
        "no-bitwise": "off",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-console": "error",
        "no-continue": "off",
        "no-delete-var": "error",
        "no-div-regex": "error",
        "no-else-return": ["error", { allowElseIf: false }],
        "no-empty": "error",
        "no-empty-function": "error",
        "no-empty-static-block": "error",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-boolean-cast": [
            "error",
            { enforceForInnerExpressions: true },
        ],
        "no-extra-label": "error",
        "no-global-assign": "error",
        "no-implicit-coercion": ["error", { disallowTemplateShorthand: true }],
        "no-implicit-globals": "error",
        "no-implied-eval": "error",
        "no-inline-comments": ["error", { ignorePattern: "@type" }],
        "no-invalid-this": "error",
        "no-iterator": "error",
        "no-label-var": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-lonely-if": "error",
        "no-loop-func": "error",
        "no-magic-numbers": "off",
        "no-multi-assign": "error",
        "no-multi-str": "error",
        "no-negated-condition": "error",
        "no-nested-ternary": "off",
        "no-new": "error",
        "no-new-func": "error",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-object-constructor": "error",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-param-reassign": [
            "error",
            {
                props: true,
                ignorePropertyModificationsFor: ["input"],
            },
        ],
        "no-plusplus": "off",
        "no-proto": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-restricted-exports": "off",
        "no-restricted-globals": "off",
        "no-restricted-imports": "off",
        "no-restricted-properties": "off",
        "no-restricted-syntax": [
            "error",
            "DebuggerStatement",
            "EmptyStatement",
            "ForInStatement",
            "LabeledStatement",
            "SequenceExpression",
            "WithStatement",
            "YieldExpression",
            "JSXIdentifier",
            "JSXNamespacedName",
            "JSXMemberExpression",
            "JSXEmptyExpression",
            "JSXExpressionContainer",
            "JSXElement",
            "JSXClosingElement",
            "JSXOpeningElement",
            "JSXAttribute",
            "JSXSpreadAttribute",
            "JSXText",
        ],
        "no-return-assign": "error",
        "no-script-url": "error",
        "no-sequences": ["error", { allowInParentheses: false }],
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-ternary": "off",
        "no-throw-literal": "error",
        "no-undef-init": "error",
        "no-undefined": "off",
        "no-underscore-dangle": "error",
        "no-unneeded-ternary": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-useless-call": "error",
        "no-useless-catch": "error",
        "no-useless-computed-key": "error",
        "no-useless-concat": "error",
        "no-useless-constructor": "error",
        "no-useless-escape": "error",
        "no-useless-rename": "error",
        "no-useless-return": "error",
        "no-var": "error",
        "no-void": "error",
        "no-warning-comments": "warn",
        "no-with": "error",
        "object-shorthand": "error",
        "one-var": ["error", "never"],
        // Désactiver cette règle et préférer unicorn/operator-assignment.
        "operator-assignment": "off",
        // Désactiver cette règle qui peut avoir des conflits avec Prettier.
        // https://github.com/prettier/eslint-plugin-prettier/issues/65
        "prefer-arrow-callback": "off",
        "prefer-const": "error",
        "prefer-destructuring": "off",
        "prefer-exponentiation-operator": "error",
        // Désactiver cette règle et préférer regexp/prefer-named-capture-group.
        "prefer-named-capture-group": "off",
        "prefer-numeric-literals": "error",
        "prefer-object-has-own": "error",
        "prefer-object-spread": "error",
        "prefer-promise-reject-errors": "error",
        "prefer-regex-literals": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        // Désactiver cette règle qui force l'utilisation des templates même
        // quand la concaténation est sur plusieurs lignes. Préférer la règle
        // "useTemplate" de Biome.
        "prefer-template": "off",
        "preserve-caught-error": ["error", { requireCatchParameter: true }],
        radix: "error",
        "require-await": "error",
        "require-unicode-regexp": ["error", { requireFlag: "v" }],
        "require-yield": "error",
        "sort-imports": [
            "error",
            {
                // Ne pas trier les imports en fonction des variables et de leur
                // type, mais préférer un tri en fonction du fichier importé.
                ignoreDeclarationSort: true,
            },
        ],
        "sort-keys": "off",
        "sort-vars": "off",
        strict: ["error", "never"],
        "symbol-description": "error",
        "vars-on-top": "off",
        yoda: ["error", "always"],

        // Layout & Formatting.
        "unicode-bom": "error",

        // Plugin eslint-plugin-array-func.
        "arrayFunc/from-map": "error",
        "arrayFunc/no-unnecessary-this-arg": "error",
        "arrayFunc/prefer-array-from": "error",
        "arrayFunc/avoid-reverse": "error",
        "arrayFunc/prefer-flat-map": "error",
        "arrayFunc/prefer-flat": "error",

        // Plugin @eslint-community/eslint-plugin-eslint-comments.
        // Best Practices.
        "comments/disable-enable-pair": ["error", { allowWholeFile: true }],
        "comments/no-aggregating-enable": "error",
        "comments/no-duplicate-disable": "error",
        "comments/no-unlimited-disable": "error",
        // Désactiver cette règle, car ESLint remonte déjà ces problèmes (avec
        // l'option reportUnusedInlineConfigs).
        "comments/no-unused-enable": "off",

        // Stylistic Issues.
        "comments/no-restricted-disable": "error",
        "comments/no-use": [
            "error",
            {
                allow: [
                    "eslint-disable",
                    "eslint-disable-next-line",
                    "eslint-enable",
                ],
            },
        ],
        "comments/require-description": "off",

        // Plugin eslint-plugin-import-x.
        // Helpful warnings.
        "importX/export": "error",
        "importX/no-deprecated": "error",
        "importX/no-empty-named-blocks": "error",
        "importX/no-extraneous-dependencies": [
            "error",
            {
                devDependencies: [
                    ".script/**/*.js",
                    "test/**/*.js",
                    "{.,}**/{.,}*.config.js",
                ],
            },
        ],
        "importX/no-mutable-exports": "error",
        "importX/no-named-as-default": "error",
        "importX/no-named-as-default-member": "off",
        "importX/no-rename-default": "error",
        // https://github.com/un-ts/eslint-plugin-import-x/pull/457
        "importX/no-unused-modules": [
            "error",
            {
                missingExports: true,
                unusedExports: true,
                suppressMissingFileEnumeratorAPIWarning: true,
            },
        ],

        // Module systems.
        // Désactiver cette règle et laisser la règle no-undef remonter les
        // erreurs, car les méthodes define() et require() ne sont pas définies.
        "importX/no-amd": "off",
        // Désactiver cette règle et préférer unicorn/prefer-module.
        "importX/no-commonjs": "off",
        "importX/no-import-module-exports": "off",
        "importX/no-nodejs-modules": "error",
        "importX/unambiguous": "off",

        // Static analysis.
        "importX/default": "error",
        "importX/named": "error",
        "importX/namespace": "error",
        "importX/no-absolute-path": "error",
        "importX/no-cycle": ["error", { ignoreExternal: true }],
        // Désactiver cette règle, car la méthode require() est déjà interdite.
        "importX/no-dynamic-require": "off",
        "importX/no-internal-modules": "off",
        "importX/no-relative-packages": "error",
        "importX/no-relative-parent-imports": "off",
        "importX/no-restricted-paths": "off",
        "importX/no-self-import": "error",
        "importX/no-unresolved": ["error", { caseSensitiveStrict: true }],
        "importX/no-useless-path-segments": "error",
        "importX/no-webpack-loader-syntax": "error",

        // Style guide.
        // Ne pas activer cette règle qui s'applique seulement à Flow et
        // TypeScript.
        "importX/consistent-type-specifier-style": "off",
        // Ne pas activer cette règle qui est utile seulement avec webpack.
        "importX/dynamic-import-chunkname": "off",
        "importX/exports-last": "off",
        "importX/extensions": ["error", "ignorePackages"],
        "importX/first": "error",
        "importX/group-exports": "off",
        "importX/max-dependencies": "off",
        "importX/newline-after-import": "error",
        "importX/no-anonymous-default-export": "error",
        "importX/no-default-export": "off",
        "importX/no-duplicates": "error",
        "importX/no-named-default": "error",
        "importX/no-named-export": "off",
        "importX/no-namespace": "off",
        "importX/no-unassigned-import": [
            "error",
            { allow: ["**/polyfills/**"] },
        ],
        "importX/order": ["error", { alphabetize: { order: "asc" } }],
        "importX/prefer-default-export": "off",
        "importX/prefer-namespace-import": "off",

        // Plugin eslint-plugin-jsdoc.
        "jsdoc/check-access": "error",
        "jsdoc/check-alignment": "error",
        "jsdoc/check-indentation": "off",
        "jsdoc/check-line-alignment": [
            "error",
            "always",
            {
                tags: ["param", "prop"],
                customSpacings: {
                    postDelimiter: 1,
                    postTag: 1,
                },
            },
        ],
        "jsdoc/check-param-names": "error",
        "jsdoc/check-property-names": "error",
        "jsdoc/check-syntax": "error",
        "jsdoc/check-tag-names": "error",
        "jsdoc/check-template-names": "error",
        "jsdoc/check-types": "error",
        "jsdoc/check-values": "error",
        "jsdoc/convert-to-jsdoc-comments": "off",
        "jsdoc/empty-tags": "error",
        "jsdoc/escape-inline-tags": "error",
        "jsdoc/implements-on-classes": "error",
        "jsdoc/imports-as-dependencies": "error",
        "jsdoc/informative-docs": "error",
        // Désactiver cette règle et laisser Prettier gérer le formatage.
        "jsdoc/lines-before-block": "off",
        "jsdoc/match-description": ["error", { matchDescription: "[A-ZÉ].*" }],
        "jsdoc/match-name": "off",
        "jsdoc/multiline-blocks": "error",
        "jsdoc/no-bad-blocks": "error",
        "jsdoc/no-blank-block-descriptions": "error",
        "jsdoc/no-blank-blocks": "error",
        "jsdoc/no-defaults": "error",
        "jsdoc/no-missing-syntax": "off",
        "jsdoc/no-multi-asterisks": "error",
        "jsdoc/no-restricted-syntax": "off",
        "jsdoc/no-types": "off",
        "jsdoc/no-undefined-types": "error",
        "jsdoc/normalize-see-links": "error",
        "jsdoc/prefer-import-tag": "error",
        "jsdoc/reject-any-type": "off",
        "jsdoc/reject-function-type": "off",
        "jsdoc/require-asterisk-prefix": "error",
        "jsdoc/require-description": "error",
        "jsdoc/require-description-complete-sentence": "off",
        "jsdoc/require-example": "off",
        "jsdoc/require-file-overview": "off",
        "jsdoc/require-hyphen-before-param-description": ["error", "never"],
        "jsdoc/require-jsdoc": "error",
        // Désactiver ces deux règles, car l'annotation @next n'est pas
        // standard.
        "jsdoc/require-next-description": "off",
        "jsdoc/require-next-type": "off",
        "jsdoc/require-param": [
            "error",
            {
                checkRestProperty: true,
                checkGetters: true,
                checkSetters: true,
                checkDestructuredRoots: true,
            },
        ],
        "jsdoc/require-param-description": "error",
        "jsdoc/require-param-name": "error",
        "jsdoc/require-param-type": "error",
        "jsdoc/require-property": "error",
        "jsdoc/require-property-description": "error",
        "jsdoc/require-property-name": "error",
        "jsdoc/require-property-type": "error",
        // Désactiver cette règle, car l'annotation @rejects n'est pas standard.
        "jsdoc/require-rejects": "off",
        "jsdoc/require-returns": "off",
        "jsdoc/require-returns-check": "error",
        "jsdoc/require-returns-description": "error",
        "jsdoc/require-returns-type": "error",
        "jsdoc/require-tags": "off",
        "jsdoc/require-template": "error",
        "jsdoc/require-template-description": "error",
        "jsdoc/require-throws": "error",
        "jsdoc/require-throws-description": "error",
        "jsdoc/require-throws-type": "error",
        "jsdoc/require-yields": "error",
        "jsdoc/require-yields-check": "error",
        "jsdoc/require-yields-description": "error",
        "jsdoc/require-yields-type": "error",
        "jsdoc/sort-tags": "error",
        "jsdoc/tag-lines": ["error", "never", { startLines: 1 }],
        "jsdoc/text-escaping": "off",
        "jsdoc/ts-method-signature-style": "error",
        "jsdoc/ts-no-empty-object-type": "error",
        "jsdoc/ts-no-unnecessary-template-expression": "error",
        "jsdoc/ts-prefer-function-type": "error",
        // Désactiver cette règle qui est expérimentale.
        "jsdoc/type-formatting": "off",
        "jsdoc/valid-types": "error",

        // Plugin eslint-plugin-no-unsanitized.
        "noUnsanitized/method": "error",
        "noUnsanitized/property": "error",

        // Plugin eslint-plugin-promise.
        "promise/always-return": "off",
        "promise/avoid-new": "off",
        "promise/catch-or-return": "off",
        "promise/no-callback-in-promise": "error",
        "promise/no-multiple-resolved": "error",
        "promise/no-native": "off",
        "promise/no-nesting": "error",
        "promise/no-new-statics": "error",
        "promise/no-promise-in-callback": "error",
        "promise/no-return-in-finally": "error",
        "promise/no-return-wrap": "error",
        "promise/param-names": "error",
        "promise/prefer-await-to-callbacks": "off",
        "promise/prefer-await-to-then": ["error", { strict: true }],
        "promise/prefer-catch": "error",
        "promise/spec-only": "error",
        "promise/valid-params": "error",

        // Plugin eslint-plugin-regexp.
        // Possible Errors.
        "regexp/no-contradiction-with-assertion": "error",
        "regexp/no-control-character": "error",
        "regexp/no-dupe-disjunctions": "error",
        "regexp/no-empty-alternative": "error",
        "regexp/no-empty-capturing-group": "error",
        "regexp/no-empty-character-class": "error",
        "regexp/no-empty-group": "error",
        "regexp/no-empty-lookarounds-assertion": "error",
        "regexp/no-escape-backspace": "error",
        "regexp/no-invalid-regexp": "error",
        "regexp/no-lazy-ends": "error",
        "regexp/no-misleading-capturing-group": "error",
        "regexp/no-misleading-unicode-character": "error",
        "regexp/no-missing-g-flag": "error",
        "regexp/no-optional-assertion": "error",
        "regexp/no-potentially-useless-backreference": "error",
        "regexp/no-super-linear-backtracking": "error",
        "regexp/no-super-linear-move": "off",
        "regexp/no-useless-assertions": "error",
        "regexp/no-useless-backreference": "error",
        "regexp/no-useless-dollar-replacements": "error",
        "regexp/strict": "error",

        // Best Practices.
        "regexp/confusing-quantifier": "error",
        "regexp/control-character-escape": "error",
        "regexp/negation": "error",
        "regexp/no-dupe-characters-character-class": "error",
        "regexp/no-empty-string-literal": "error",
        "regexp/no-extra-lookaround-assertions": "error",
        "regexp/no-invisible-character": "error",
        "regexp/no-legacy-features": "error",
        "regexp/no-non-standard-flag": "error",
        "regexp/no-obscure-range": "error",
        "regexp/no-octal": "error",
        "regexp/no-standalone-backslash": "error",
        "regexp/no-trivially-nested-assertion": "error",
        "regexp/no-trivially-nested-quantifier": "error",
        "regexp/no-unused-capturing-group": "error",
        "regexp/no-useless-character-class": "error",
        "regexp/no-useless-flag": "error",
        "regexp/no-useless-lazy": "error",
        "regexp/no-useless-quantifier": "error",
        "regexp/no-useless-range": "error",
        "regexp/no-useless-set-operand": "error",
        "regexp/no-useless-string-literal": "error",
        "regexp/no-useless-two-nums-quantifier": "error",
        "regexp/no-zero-quantifier": "error",
        "regexp/optimal-lookaround-quantifier": "error",
        "regexp/optimal-quantifier-concatenation": "error",
        "regexp/prefer-escape-replacement-dollar-char": "error",
        "regexp/prefer-predefined-assertion": "error",
        "regexp/prefer-quantifier": "error",
        "regexp/prefer-range": "error",
        "regexp/prefer-regexp-exec": "error",
        "regexp/prefer-regexp-test": "error",
        "regexp/prefer-set-operation": "error",
        // Désactiver cette règle qui est quasi-identique à la règle
        // "require-unicode-regexp" (seule la position de la notification est
        // différente).
        "regexp/require-unicode-regexp": "off",
        "regexp/simplify-set-operations": "error",
        "regexp/sort-alternatives": "error",
        "regexp/use-ignore-case": "error",

        // Stylistic Issues.
        "regexp/grapheme-string-literal": "error",
        "regexp/hexadecimal-escape": "off",
        "regexp/letter-case": [
            "error",
            {
                unicodeEscape: "uppercase",
                hexadecimalEscape: "uppercase",
            },
        ],
        "regexp/match-any": "error",
        "regexp/no-useless-escape": "error",
        "regexp/no-useless-non-capturing-group": "error",
        "regexp/prefer-character-class": "error",
        "regexp/prefer-d": ["error", { insideCharacterClass: "range" }],
        "regexp/prefer-lookaround": "error",
        "regexp/prefer-named-backreference": "error",
        "regexp/prefer-named-capture-group": "error",
        "regexp/prefer-named-replacement": "error",
        "regexp/prefer-plus-quantifier": "error",
        "regexp/prefer-question-quantifier": "error",
        "regexp/prefer-result-array-groups": "error",
        "regexp/prefer-star-quantifier": "error",
        "regexp/prefer-unicode-codepoint-escapes": "error",
        "regexp/prefer-w": "error",
        "regexp/sort-character-class-elements": "error",
        "regexp/sort-flags": "error",
        "regexp/unicode-escape": "error",
        "regexp/unicode-property": "error",

        // Plugin eslint-plugin-security.
        "security/detect-bidi-characters": "error",
        "security/detect-buffer-noassert": "error",
        "security/detect-child-process": "error",
        "security/detect-disable-mustache-escape": "error",
        "security/detect-eval-with-expression": "error",
        "security/detect-new-buffer": "error",
        "security/detect-no-csrf-before-method-override": "error",
        "security/detect-non-literal-fs-filename": "off",
        "security/detect-non-literal-regexp": "off",
        "security/detect-non-literal-require": "error",
        "security/detect-object-injection": "off",
        "security/detect-possible-timing-attacks": "error",
        "security/detect-pseudoRandomBytes": "error",
        "security/detect-unsafe-regex": "off",

        // Plugin eslint-plugin-unicorn.
        "unicorn/better-dom-traversing": "error",
        "unicorn/catch-error-name": ["error", { ignore: [/^err$/v, /^e$/v] }],
        "unicorn/class-reference-in-static-methods": "error",
        "unicorn/comment-content": ["error", { checkUniformCase: false }],
        "unicorn/consistent-arrow-return-style": "off",
        "unicorn/consistent-assert": "error",
        "unicorn/consistent-boolean-name": "off",
        "unicorn/consistent-class-member-order": "off",
        "unicorn/consistent-compound-words": "error",
        "unicorn/consistent-conditional-object-spread": "error",
        "unicorn/consistent-date-clone": "error",
        "unicorn/consistent-destructuring": "error",
        "unicorn/consistent-empty-array-spread": "error",
        "unicorn/consistent-existence-index-check": "error",
        "unicorn/consistent-export-decorator-position": "error",
        "unicorn/consistent-function-scoping": "error",
        "unicorn/consistent-function-style": [
            "error",
            {
                default: "arrow-function",
                defaultExport: "declaration",
                namedFunctions: "arrow-function",
                namedExports: "arrow-function",
                callbacks: "arrow-function",
                objectProperties: "ignore",
                reassignedVariables: "arrow-function",
                typedVariables: "arrow-function",
            },
        ],
        "unicorn/consistent-json-file-read": "error",
        "unicorn/consistent-optional-chaining": "error",
        "unicorn/consistent-template-literal-escape": "error",
        "unicorn/consistent-tuple-labels": "error",
        "unicorn/custom-error-definition": "error",
        "unicorn/default-export-style": "error",
        "unicorn/dom-node-dataset": "error",
        // Laisser Prettier gérer cette règle.
        "unicorn/empty-brace-spaces": "off",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/expiring-todo-comments": "off",
        "unicorn/explicit-length-check": "off",
        "unicorn/explicit-timer-delay": "error",
        "unicorn/filename-case": "error",
        "unicorn/id-match": "off",
        "unicorn/import-style": "error",
        "unicorn/isolated-functions": "off",
        "unicorn/iteration-fallback-style": "off",
        "unicorn/logical-assignment-operators": "off",
        "unicorn/max-nested-calls": "off",
        "unicorn/name-replacements": "off",
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-accessor-recursion": "error",
        "unicorn/no-accidental-bitwise-operator": "error",
        "unicorn/no-anonymous-default-export": "error",
        "unicorn/no-array-callback-reference": "off",
        "unicorn/no-array-concat-in-loop": "error",
        "unicorn/no-array-fill-with-reference-type": "error",
        "unicorn/no-array-from-fill": "error",
        "unicorn/no-array-front-mutation": "off",
        "unicorn/no-array-method-this-argument": "error",
        "unicorn/no-array-reduce": "off",
        "unicorn/no-array-reverse": "error",
        "unicorn/no-array-sort": "error",
        "unicorn/no-array-sort-for-min-max": "error",
        "unicorn/no-array-splice": "error",
        "unicorn/no-asterisk-prefix-in-documentation-comments": "off",
        "unicorn/no-async-promise-finally": "error",
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-await-in-promise-methods": "error",
        "unicorn/no-barrel-files": "off",
        "unicorn/no-blob-to-file": "error",
        "unicorn/no-boolean-sort-comparator": "error",
        "unicorn/no-break-in-nested-loop": "off",
        "unicorn/no-canvas-to-image": "error",
        "unicorn/no-chained-comparison": "error",
        "unicorn/no-collection-bracket-access": "error",
        "unicorn/no-computed-property-existence-check": "error",
        "unicorn/no-confusing-array-splice": "error",
        "unicorn/no-confusing-array-with": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-constant-zero-expression": "error",
        "unicorn/no-double-comparison": "error",
        "unicorn/no-declarations-before-early-exit": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/no-duplicate-loops": "off",
        "unicorn/no-duplicate-if-branches": "error",
        "unicorn/no-duplicate-logical-operands": "error",
        "unicorn/no-duplicate-set-values": "error",
        // Autoriser les fichiers avec seulement des définitions de types JSDoc.
        "unicorn/no-empty-file": ["error", { allowComments: true }],
        "unicorn/no-error-property-assignment": "error",
        "unicorn/no-exports-in-scripts": "error",
        "unicorn/no-for-each": "off",
        "unicorn/no-for-loop": "error",
        "unicorn/no-global-object-property-assignment": "off",
        "unicorn/no-immediate-mutation": "error",
        "unicorn/no-impossible-length-comparison": "error",
        "unicorn/no-incorrect-query-selector": "error",
        "unicorn/no-incorrect-template-string-interpolation": "error",
        "unicorn/no-instanceof-builtins": "error",
        "unicorn/no-invalid-argument-count": "error",
        "unicorn/no-invalid-character-comparison": "error",
        "unicorn/no-invalid-fetch-options": "error",
        "unicorn/no-invalid-file-input-accept": "error",
        "unicorn/no-invalid-remove-event-listener": "error",
        "unicorn/no-invalid-well-known-symbol-methods": "error",
        "unicorn/no-keyword-prefix": "error",
        "unicorn/no-late-current-target-access": "error",
        "unicorn/no-late-event-control": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/no-loop-iterable-mutation": "error",
        "unicorn/no-magic-array-flat-depth": "error",
        "unicorn/no-manually-wrapped-comments": "off",
        "unicorn/no-mismatched-map-key": "error",
        "unicorn/no-misrefactored-assignment": "error",
        // Désactiver cette règle qui s'applique sur des fichiers Markdown.
        "unicorn/no-missing-local-resource": "off",
        "unicorn/no-multiple-promise-resolver-calls": "error",
        "unicorn/no-named-default": "error",
        "unicorn/no-negated-array-predicate": "error",
        "unicorn/no-negated-comparison": "error",
        // Utiliser la règle no-negated-condition d'ESLint, car celle d'unicorn
        // apporte seulement la correction automatique.
        "unicorn/no-negated-condition": "off",
        "unicorn/no-negation-in-equality-check": "error",
        "unicorn/no-nested-ternary": "off",
        "unicorn/no-new-array": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-non-function-verb-prefix": "error",
        // Préférer vérifier l'utilisation de propriétés avec TypeScript.
        "unicorn/no-nonstandard-builtin-properties": "off",
        "unicorn/no-null": "error",
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/no-object-methods-with-collections": "error",
        "unicorn/no-optional-chaining-on-undeclared-variable": "error",
        "unicorn/no-process-exit": "error",
        "unicorn/no-redundant-comparison": "error",
        "unicorn/no-return-array-push": "error",
        "unicorn/no-selector-as-dom-name": "error",
        // Désactiver cette règle qui s'applique sur les fichiers CSS.
        "unicorn/no-shorthand-property-overrides": "off",
        "unicorn/no-single-promise-in-promise-methods": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/no-subtraction-comparison": "error",
        "unicorn/no-thenable": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-this-outside-of-class": "off",
        "unicorn/no-top-level-assignment-in-function": "off",
        "unicorn/no-top-level-side-effects": "error",
        // Désactiver cette règle qui s'applique sur les fichiers CSS.
        "unicorn/no-transition-all": "off",
        "unicorn/no-typeof-undefined": [
            "error",
            { checkGlobalVariables: true },
        ],
        "unicorn/no-uncalled-method": "error",
        "unicorn/no-undeclared-class-members": "error",
        "unicorn/no-unnecessary-array-flat-depth": "error",
        "unicorn/no-unnecessary-array-splice-count": "error",
        "unicorn/no-unnecessary-await": "error",
        "unicorn/no-unnecessary-boolean-comparison": "error",
        "unicorn/no-unnecessary-fetch-options": "error",
        "unicorn/no-unnecessary-global-this": "error",
        "unicorn/no-unnecessary-nested-ternary": "error",
        "unicorn/no-unnecessary-polyfills": "error",
        "unicorn/no-unnecessary-slice-end": "error",
        "unicorn/no-unnecessary-splice": "error",
        "unicorn/no-unnecessary-string-trim": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unreadable-for-of-expression": "off",
        "unicorn/no-unreadable-iife": "error",
        "unicorn/no-unreadable-new-expression": "off",
        "unicorn/no-unreadable-object-destructuring": "error",
        "unicorn/no-unsafe-buffer-conversion": "error",
        "unicorn/no-unsafe-dom-html": "error",
        "unicorn/no-unsafe-promise-all-settled-values": "error",
        "unicorn/no-unsafe-property-key": "error",
        "unicorn/no-unsafe-sqlite-interpolation": "error",
        "unicorn/no-unsafe-string-replacement": "error",
        "unicorn/no-unused-array-method-return": "error",
        "unicorn/no-unused-properties": "error",
        "unicorn/no-useless-boolean-cast": "error",
        "unicorn/no-useless-coercion": "error",
        "unicorn/no-useless-collection-argument": "error",
        "unicorn/no-useless-compound-assignment": "error",
        "unicorn/no-useless-concat": "error",
        "unicorn/no-useless-continue": "error",
        "unicorn/no-useless-delete-check": "error",
        "unicorn/no-useless-else": "error",
        "unicorn/no-useless-error-capture-stack-trace": "error",
        "unicorn/no-useless-fallback-in-spread": "error",
        "unicorn/no-useless-iterator-to-array": "error",
        "unicorn/no-useless-length-check": "error",
        "unicorn/no-useless-logical-operand": "error",
        "unicorn/no-useless-override": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "unicorn/no-useless-recursion": "error",
        "unicorn/no-useless-re-export": "error",
        "unicorn/no-useless-spread": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-useless-template-literals": "error",
        "unicorn/no-useless-undefined": "off",
        "unicorn/no-xor-as-exponentiation": "error",
        "unicorn/no-zero-fractions": "error",
        // Laisser Prettier gérer cette règle.
        "unicorn/number-literal-case": "off",
        "unicorn/numeric-separators-style": "error",
        "unicorn/operator-assignment": "error",
        "unicorn/prefer-abort-signal-any": "error",
        "unicorn/prefer-abort-signal-timeout": "error",
        "unicorn/prefer-add-event-listener": "error",
        "unicorn/prefer-add-event-listener-options": "error",
        "unicorn/prefer-aggregate-error": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-array-from-async": "error",
        "unicorn/prefer-array-from-map": "error",
        "unicorn/prefer-array-from-range": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-array-iterable-methods": "error",
        "unicorn/prefer-array-last-methods": "error",
        "unicorn/prefer-array-slice": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-at": "error",
        // Préférer la règle promise/prefer-await-to-then.
        "unicorn/prefer-await": "off",
        "unicorn/prefer-bigint-literals": "error",
        "unicorn/prefer-blob-reading-methods": "error",
        "unicorn/prefer-block-statement-over-iife": "error",
        "unicorn/prefer-boolean-return": "error",
        "unicorn/prefer-class-fields": "error",
        "unicorn/prefer-classlist-toggle": "error",
        "unicorn/prefer-code-point": "error",
        "unicorn/prefer-continue": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/prefer-direct-iteration": "error",
        // Désactiver cette règle, car "using" n'est pas disponible dans Node.js v22.
        "unicorn/prefer-dispose": "off",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-html-methods": [
            "error",
            { checkSetHTML: true },
        ],
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-dom-node-replace-children": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-early-return": "error",
        "unicorn/prefer-else-if": "error",
        "unicorn/prefer-error-is-error": "error",
        "unicorn/prefer-event-target": "error",
        // Désactiver cette règle qui s'applique sur les fichiers CSS.
        "unicorn/prefer-explicit-viewport-units": "off",
        "unicorn/prefer-export-from": ["error", { checkUsedVariables: false }],
        "unicorn/prefer-flat-math-min-max": "error",
        "unicorn/prefer-get-or-insert-computed": "error",
        "unicorn/prefer-global-number-constants": "error",
        "unicorn/prefer-global-this": "error",
        "unicorn/prefer-group-by": "error",
        "unicorn/prefer-has-check": "error",
        "unicorn/prefer-hoisting-branch-code": "error",
        "unicorn/prefer-https": "error",
        "unicorn/prefer-import-meta-properties": "error",
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-includes-over-repeated-comparisons": "error",
        "unicorn/prefer-identifier-import-export-specifiers": "error",
        "unicorn/prefer-iterable-in-constructor": "error",
        "unicorn/prefer-iterator-concat": "error",
        "unicorn/prefer-iterator-helpers": "error",
        "unicorn/prefer-iterator-to-array": "error",
        "unicorn/prefer-iterator-to-array-at-end": "error",
        "unicorn/prefer-json-parse-buffer": "off",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-location-assign": "error",
        "unicorn/prefer-logical-operator-over-ternary": "error",
        "unicorn/prefer-math-abs": "error",
        "unicorn/prefer-math-constants": "error",
        "unicorn/prefer-math-min-max": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-map-from-entries": "error",
        "unicorn/prefer-minimal-ternary": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-module": "error",
        "unicorn/prefer-native-coercion-functions": "error",
        "unicorn/prefer-negative-index": "error",
        // Désactiver cette règle et préférer la règle "n/prefer-node-protocol".
        "unicorn/prefer-node-protocol": "off",
        "unicorn/prefer-number-coercion": "error",
        "unicorn/prefer-number-is-safe-integer": "error",
        "unicorn/prefer-number-properties": "error",
        "unicorn/prefer-object-define-properties": "error",
        "unicorn/prefer-object-destructuring-defaults": "error",
        "unicorn/prefer-object-from-entries": "error",
        "unicorn/prefer-object-iterable-methods": "error",
        "unicorn/prefer-observer-apis": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/prefer-path2d": "error",
        "unicorn/prefer-private-class-fields": "error",
        "unicorn/prefer-promise-try": "error",
        "unicorn/prefer-promise-with-resolvers": "error",
        "unicorn/prefer-prototype-methods": "error",
        "unicorn/prefer-query-selector": "error",
        "unicorn/prefer-queue-microtask": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-regexp-escape": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-response-static-json": "error",
        "unicorn/prefer-scoped-selector": "off",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-set-methods": "error",
        "unicorn/prefer-set-size": "error",
        "unicorn/prefer-short-arrow-method": "off",
        "unicorn/prefer-simple-condition-first": "off",
        "unicorn/prefer-simple-sort-comparator": "error",
        "unicorn/prefer-simplified-conditions": "error",
        "unicorn/prefer-single-array-predicate": "error",
        "unicorn/prefer-single-call": "error",
        "unicorn/prefer-single-object-destructuring": "error",
        "unicorn/prefer-single-replace": "error",
        "unicorn/prefer-smaller-scope": "error",
        "unicorn/prefer-split-limit": "error",
        "unicorn/prefer-spread": "off",
        "unicorn/prefer-string-match-all": "error",
        "unicorn/prefer-string-pad-start-end": "error",
        "unicorn/prefer-string-raw": "error",
        "unicorn/prefer-string-repeat": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/prefer-switch": "off",
        // Désactiver cette règle, car Temporal n'est pas disponible dans Node.js v22.
        "unicorn/prefer-temporal": "off",
        "unicorn/prefer-ternary": "off",
        "unicorn/prefer-then-catch": "error",
        "unicorn/prefer-toggle-attribute": "error",
        "unicorn/prefer-top-level-await": "error",
        "unicorn/prefer-type-error": "error",
        // Désactiver cette règle qui vérifie seulement les types TypeScript.
        "unicorn/prefer-type-literal-last": "off",
        "unicorn/prefer-uint8array-base64": "error",
        "unicorn/prefer-unary-minus": "error",
        "unicorn/prefer-unicode-code-point-escapes": "error",
        "unicorn/prefer-url-can-parse": "error",
        "unicorn/prefer-url-href": "error",
        "unicorn/prefer-url-search-parameters": "error",
        "unicorn/prefer-while-loop-condition": "error",
        "unicorn/relative-url-style": "error",
        "unicorn/require-array-join-separator": "off",
        "unicorn/require-array-sort-compare": "error",
        "unicorn/require-css-escape": "error",
        // Désactiver cette règle qui s'applique sur les fichiers markdown.
        "unicorn/require-frontmatter-fields": "off",
        "unicorn/require-module-attributes": "error",
        "unicorn/require-module-specifiers": "error",
        "unicorn/require-number-to-fixed-digits-argument": "off",
        "unicorn/require-passive-events": "error",
        // Désactiver cette règle, car il y a des faux-positifs avec d'autres
        // méthodes postMessage().
        // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/require-post-message-target-origin.md
        "unicorn/require-post-message-target-origin": "off",
        "unicorn/require-proxy-trap-boolean-return": "error",
        "unicorn/single-line-block-comment-style": "off",
        "unicorn/string-content": "off",
        "unicorn/switch-case-braces": ["error", "avoid"],
        "unicorn/switch-case-break-position": "error",
        "unicorn/template-indent": [
            "error",
            // Configurer la règle pour qu'elle soit compatible avec Prettier.
            // https://github.com/prettier/eslint-config-prettier#unicorntemplate-indent
            {
                tags: ["outdent", "dedent", "sql", "styled"],
                functions: ["dedent", "stripIndent"],
                selectors: [],
                comments: ["indent"],
            },
        ],
        "unicorn/text-encoding-identifier-case": "error",
        "unicorn/throw-new-error": "error",
        "unicorn/try-complexity": "off",
    },

    settings: {
        jsdoc: {
            preferredTypes: {
                ".<>": "<>",
                "Array<>": "[]",
                object: "Object",
                "object<>": "Object<>",
            },
            tagNamePreference: {
                virtual: "abstract",
                extends: "augments",
                constructor: "class",
                const: "constant",
                defaultvalue: "default",
                desc: "description",
                host: "external",
                fileoverview: "file",
                overview: "file",
                emits: "fires",
                func: "function",
                method: "function",
                var: "member",
                arg: "param",
                argument: "param",
                property: "prop",
                return: "returns",
                exception: "throws",
                yield: "yields",
                linkcode: "link",
                linkplain: "link",
            },
        },
    },
};
