name: Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      # Ajouter cette permission pour le OpenID Connect (OIDC).
      # https://docs.npmjs.com/trusted-publishers
      id-token: write
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json

      # Si la PR (pull request) a été créée ou modifiée : formatter les fichiers
      # modifiés par release-please, car ils ne respectent plus le formatage de
      # Prettier (via Metalint).
      # https://github.com/googleapis/release-please/issues/1802
      - name: Checkout repository
        if: ${{ steps.release.outputs.pr }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true
          ref: ${{ fromJSON(steps.release.outputs.pr).headBranchName }}
          # Récupérer deux commits sinon la réparation du commit (pour le
          # formatage) rompt le lien entre la branche de la release et la
          # branche main.
          fetch-depth: 2

      - name: Configure Git user
        if: ${{ steps.release.outputs.pr }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Setup Node.js
        if: ${{ steps.release.outputs.pr }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          package-manager-cache: false

      - name: Install dependencies
        if: ${{ steps.release.outputs.pr }}
        run: npm ci

      - name: Format files
        if: ${{ steps.release.outputs.pr }}
        run: >
          npm run lint:fix -- .release-please/manifest.json CHANGELOG.md
          jsr.json package.json package-lock.json

      - name: Commit and push
        if: ${{ steps.release.outputs.pr }}
        run: |
          git commit --all --amend --no-edit
          git push --force

      # Si la release a été créée : publier le paquet dans npm et JSR.
      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - name: Install dependencies and build declaration files (d.ts)
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Publish in npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish

      - name: Publish in JSR
        if: ${{ steps.release.outputs.release_created }}
        run: npx jsr publish

      - name: Env package name
        if: ${{ steps.release.outputs.release_created }}
        # Enlever les guillemets qui entourent le nom du paquet.
        # https://github.com/npm/cli/issues/5508
        run: echo "NPM_NAME=$(npm pkg get name | tr -d \")" >> $GITHUB_ENV

      - name: Download tarball from npm
        if: ${{ steps.release.outputs.release_created }}
        env:
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
          NPM_NAME: ${{ env.NPM_NAME }}
        run: npm pack --min-release-age 0 ${NPM_NAME}@${TAG_NAME}

      - name: Upload tarball to release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
          NPM_NAME: ${{ env.NPM_NAME }}
        run: gh release upload ${TAG_NAME} ${NPM_NAME}-*.tgz
